### ISSUE TITLE
Deleting a Patient from DB through DoctorView

### ISSUE THREAD

**Issue by Eecekkaratas** [Saeed-Muhaisen/PharmacyProject#4]
I cannot delete a patient from database from DoctorView it gives an sql error, is this a functionality or a bug?

**Comment by Saeed-Muhaisen** [comment]
It was a bug but i fixed it. 
Initially all doctors had access to all patients info like name and id, now every doctor must create a patient with his name and id.
If we have 2 doctors having same patient and first doctor decide to delete this patient, then second doctor wont be affected.

Also another reason why it wasn't working is because of foreign key constraint, we couldn't delete a patient with active prescriptions so the prescription is not lost, i removed connection between these two tables, now even if patient is deleted prescription is never lost.
